services:
  # Contenedor de Base de Datos
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: asistencia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Opcional: solo si quieres conectarte desde DBeaver en tu PC

  # Contenedor de tu Web + Scraper
  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/asistencia_db
      - APP_PASSWORD=${APP_PASSWORD} # Tu contraseña para entrar a la web
    depends_on:
      - db
    volumes:
      - ./web:/app  # Para que si cambias código, se actualice sin reconstruir

volumes:
  postgres_data:
